language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
install:
  - pip install .[testing]
script:
  - pytest --cov=logging_json --cov-fail-under=100
deploy:
  provider: pypi
  username: __token__
  edge: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
